// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/article/[slug].ts";
import * as $1 from "./routes/arch/[slug].tsx";
import * as $2 from "./routes/art/[slug].tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/ImageDisplay.tsx";
import * as $$1 from "./islands/SidebarSwitch.tsx";

const manifest = {
  routes: {
    "./routes/api/article/[slug].ts": $0,
    "./routes/arch/[slug].tsx": $1,
    "./routes/art/[slug].tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/ImageDisplay.tsx": $$0,
    "./islands/SidebarSwitch.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
